### ISSUE TITLE
Npm start fails

### ISSUE THREAD

**Issue by FRosner** [Husterknupp/fxck#1]
```
frosner:fxck/ (master*) $ npm start

> fxck@1.0.0-SNAPSHOT start /Users/frosner/Documents/projects/fxck
> node index.js

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/frosner/Documents/projects/fxck/index.js:1:77)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! fxck@1.0.0-SNAPSHOT start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fxck@1.0.0-SNAPSHOT start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fxck package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fxck
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/frosner/Documents/projects/fxck/npm-debug.log
```

**Comment by Husterknupp** [comment]
please run npm install to update the node modules before you start the app. Put it in the reae with last commit
